import { useState } from 'react';
import { ArrowRight, VideoCamera as Video } from '@phosphor-icons/react';
import { AREAS, STAGES, PRIORITIES } from '../../constants/workflow';
import { AppSelect } from '../common/AppSelect';
import { SelectField, Modal } from '../common/ui';
import { Field, TextField, TextAreaField } from '../common/Field';

export function ReviewModal({ onClose, onSave, meetings = [], team = [] }) {
  const teamNames = team.map(t => t.name);
  const [form, setForm] = useState({title:'',description:'',area:'Design',priority:'Major',status:'Open',stage:'Planning',assignee:'Aria',startDate:'',due:'2026-09-18',meetingId:''});
  const edit = (key,val)=>setForm(x=>({...x,[key]:val}));
  const meetingOptions = [{ value: '', label: 'No related meeting' }, ...meetings.map(m => ({ value: m.id, label: m.title }))];
  return <Modal title="Create task" subtitle="Add a new task to this project. You can fill in more details after creation." onClose={onClose}><form onSubmit={e=>{e.preventDefault(); if(form.title.trim())onSave(form)}}><TextField label="Title" autoFocus value={form.title} onChange={e=>edit('title',e.target.value)} placeholder="e.g. Fix pagination bug on list view" required/><TextAreaField label="Description" value={form.description} onChange={e=>edit('description',e.target.value)} placeholder="Add context, links, or acceptance criteria…"/><div className="form-grid"><SelectField label="Status" value={form.status} values={['Open','In Progress','Review','Resolved','Rejected']} onChange={v=>edit('status',v)}/><SelectField label="Priority" value={form.priority} values={PRIORITIES} onChange={v=>edit('priority',v)}/><SelectField label="Phase" value={form.stage} values={STAGES} onChange={v=>edit('stage',v)}/><SelectField label="Team" value={form.area} values={AREAS} onChange={v=>edit('area',v)}/><Field label="Assignee">{teamNames.length ? <AppSelect value={form.assignee} options={[{ value: '', label: 'Unassigned' }, ...teamNames]} onChange={v => edit('assignee', v)} placeholder="Unassigned" ariaLabel="Assignee"/> : <input className="field-input" value={form.assignee} onChange={e=>edit('assignee',e.target.value)} placeholder="Unassigned"/>}</Field><Field label="Related meeting" icon={Video}><AppSelect value={form.meetingId} options={meetingOptions} onChange={v => edit('meetingId', v)} placeholder="No related meeting" ariaLabel="Related meeting"/></Field></div><div className="form-grid"><TextField label="Start date" type="date" value={form.startDate} onChange={e=>edit('startDate',e.target.value)}/><TextField label="Due date" type="date" value={form.due} onChange={e=>edit('due',e.target.value)}/></div><div className="modal-actions"><button type="button" className="text-button" onClick={onClose}>Cancel</button><button className="primary-button">Create task <ArrowRight size={16}/></button></div></form></Modal>;
}
