import { useEffect, useState } from 'react';
import { ShieldCheck, Trash as Trash2, Users } from '@phosphor-icons/react';
import { api } from '../../api/client';
import { Wave } from '../Wave.jsx';
import { StatusPill, MetricCard, PageHeading, Empty, Modal } from '../common/ui';

export function AdminPageEnhanced({ user, setToast, requestConfirm }) {
  const confirmAction = opts => { if (requestConfirm) requestConfirm(opts); };
  const [admins, setAdmins] = useState([]); const [error, setError] = useState(''); const [loaded, setLoaded] = useState(false); const [inviteOpen, setInviteOpen] = useState(false); const [invite, setInvite] = useState({ name: '', email: '', password: '' });
  const load = () => api('/api/admin/users').then(result => setAdmins(result.users)).catch(error => setError(error.message)).finally(() => setLoaded(true)); useEffect(() => { load(); }, []);
  const submit = async event => { event.preventDefault(); try { await api('/api/admin/users', { method: 'POST', body: JSON.stringify(invite) }); setInviteOpen(false); setInvite({ name: '', email: '', password: '' }); await load(); setToast('Admin account created'); } catch (error) { setToast(error.message); } };
  const doRole = async (person, nextRole) => { try { await api(`/api/admin/users/${person.id}`, { method: 'PATCH', body: JSON.stringify({ role: nextRole }) }); await load(); setToast('Admin role updated'); } catch (error) { setToast(error.message); } };
  const role = (person, nextRole) => confirmAction({ icon: <ShieldCheck size={24}/>, title: `${nextRole === 'admin' ? 'Promote' : 'Demote'} ${person.email}?`, subtitle: nextRole === 'admin' ? 'They will gain full workspace management access.' : 'They will lose admin access and become a regular member.', confirmLabel: nextRole === 'admin' ? 'Promote' : 'Demote', onConfirm: () => doRole(person, nextRole) });
  const doRemove = async person => { try { await api(`/api/admin/users/${person.id}`, { method: 'DELETE' }); await load(); setToast('Admin removed'); } catch (error) { setToast(error.message); } };
  const remove = person => confirmAction({ danger: true, icon: <Trash2 size={24}/>, title: `Delete ${person.email}?`, subtitle: 'Their account will be permanently removed. This cannot be undone.', confirmLabel: 'Delete admin', onConfirm: () => doRemove(person) });
  const superAdmins = admins.filter(person => person.role === 'super_admin').length; const regularAdmins = admins.filter(person => person.role === 'admin').length;
  return <section className="page admin-page"><PageHeading title="Admin Management" action={<button className="primary-button" onClick={() => setInviteOpen(true)}><Users size={16}/> Invite Admin</button>}/><div className="admin-kpis"><MetricCard label="Total Admins" value={admins.length}/><MetricCard label="Super Admins" value={superAdmins}/><MetricCard label="Regular Admins" value={regularAdmins}/></div>{!loaded ? <div className="empty-state"><Wave /> Loading admins…</div> : error ? <Empty text={error}/> : <div className="table-wrap"><table><thead><tr><th>Email</th><th>Name</th><th>Role</th><th>Actions</th></tr></thead><tbody>{admins.map(person => <tr key={person.id}><td><strong>{person.email}{person.id === user.id && <small className="you">(You)</small>}</strong></td><td>{person.name}</td><td><StatusPill value={person.role === 'super_admin' ? 'Super admin' : person.role === 'admin' ? 'Admin' : 'Member'}/></td><td>{person.id !== user.id && <div className="admin-actions"><button onClick={() => role(person, person.role === 'admin' ? 'member' : 'admin')}>{person.role === 'admin' ? 'Demote' : 'Promote'}</button><button className="danger-text" onClick={() => remove(person)}>Delete</button></div>}</td></tr>)}</tbody></table></div>}{inviteOpen && <Modal title="Invite admin" subtitle="Create an admin account that can manage this workspace." onClose={() => setInviteOpen(false)}><form onSubmit={submit}><label>Name<input value={invite.name} onChange={event => setInvite({ ...invite, name: event.target.value })} required/></label><label>Email<input type="email" value={invite.email} onChange={event => setInvite({ ...invite, email: event.target.value })} required/></label><label>Temporary password (min 8 chars)<input type="password" minLength="8" value={invite.password} onChange={event => setInvite({ ...invite, password: event.target.value })} required/></label><div className="modal-actions"><button type="button" className="text-button" onClick={() => setInviteOpen(false)}>Cancel</button><button className="primary-button">Create admin</button></div></form></Modal>}</section>;
}


