import { CalendarPlus, ChatCircle, Gear, House, Kanban, MagnifyingGlass, Plus, ShieldCheck, Archive, Folder } from '@phosphor-icons/react';
import { statusFor } from '../../lib/status';

const navigation = [['Overview', House], ['All Reviews', ChatCircle], ['Board', Kanban], ['Archive', Archive], ['Settings', Gear], ['Admin Management', ShieldCheck]];

export function CommandPalette({ query, setQuery, reviews, projects, activeProjectId, onClose, onNavigate, onNewMeeting, onNewReview, onOpenReview, onSelectProject }) {
  const term = query.trim().toLowerCase();
  const matches = reviews.filter(item => `${item.title} ${item.description || ''} ${item.assignee || ''}`.toLowerCase().includes(term)).slice(0, 7);
  const filteredProjects = (projects || []).filter(item => !term || item.name.toLowerCase().includes(term)).slice(0, 6);
  const filteredNavigation = navigation.filter(([name]) => !term || name.toLowerCase().includes(term));
  const action = callback => { callback(); onClose(); };
  return <div className="command-backdrop" onMouseDown={onClose}><section className="command-palette" role="dialog" aria-modal="true" aria-label="Search and navigation" onMouseDown={event => event.stopPropagation()}><div className="command-search"><MagnifyingGlass size={18}/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search reviews, projects, or navigate…" aria-label="Search reviews, projects, or navigation"/><kbd>Esc</kbd></div><div className="command-scroll"><CommandGroup label="Quick actions"><CommandButton icon={CalendarPlus} label="Start new meeting" hint="New" onClick={() => action(onNewMeeting)}/><CommandButton icon={Plus} label="Submit new review" hint="New" onClick={() => action(onNewReview)}/></CommandGroup><CommandGroup label="Navigate">{filteredNavigation.map(([name, Icon]) => <CommandButton key={name} icon={Icon} label={name} onClick={() => action(() => onNavigate(name === 'Admin Management' ? 'Admin' : name))}/>)}</CommandGroup>{filteredProjects.length > 0 && <CommandGroup label="Projects">{filteredProjects.map(project => <CommandButton key={project.id} icon={Folder} label={project.name} hint={project.id === activeProjectId ? 'Active' : ''} onClick={() => action(() => onSelectProject(project))}/>)}</CommandGroup>}{matches.length > 0 && <CommandGroup label="Reviews">{matches.map(review => <CommandButton key={review.id} icon={ChatCircle} label={review.title} hint={statusFor(review)} onClick={() => action(() => onOpenReview(review))}/>)}</CommandGroup>}{term && !matches.length && !filteredProjects.length && !filteredNavigation.length && <p className="command-empty">No matching results.</p>}</div></section></div>;
}
function CommandGroup({ label, children }) { return <div className="command-group"><span className="command-group-label">{label}</span>{children}</div>; }
function CommandButton({ icon: Icon, label, hint, onClick }) { return <button className="command-item" onClick={onClick}><Icon size={18}/><span>{label}</span>{hint && <small>{hint}</small>}</button>; }
