import { ArrowLeft, CheckSquare, Trash, User, CalendarBlank, Flag, Users, MagicWand } from '@phosphor-icons/react';
import { AREAS, PRIORITIES } from '../../constants/workflow';

export function MeetingAiReview({ user, meeting, items, setItems, selectedCount, onBack, onCreate }) {
  const update = (id, key, value) => setItems(previous => previous.map(item => item.id === id ? { ...item, [key]: value } : item));
  const remove = id => setItems(previous => previous.map(item => item.id === id ? { ...item, keep: false } : item));
  const create = () => onCreate({ meeting: { ...meeting, ai: true, itemCount: selectedCount }, items: items.filter(item => item.keep) });
  return <section className="meeting-ai-page">
    <div className="ai-review-header"><div><button className="back-link" onClick={onBack}><ArrowLeft size={17}/> Back to editor</button><div className="ai-review-title"><span className="ai-review-icon"><MagicWand size={18}/></span><div><h1>AI Review</h1><p>{items.length} items extracted — review, edit, and select before creating</p></div></div></div><button className="back-to-editor" onClick={onBack}>Back to editor</button></div>
    <div className="ai-review-content"><div className="ai-section-label"><span>⌄ <CheckSquare size={15}/> Action Items</span><small>{selectedCount} selected</small></div><div className="ai-item-list">{items.map((item, index) => <article className={`ai-item-card${item.keep ? '' : ' discarded'}`} key={item.id}><div className="ai-item-top"><label><input type="checkbox" checked={item.keep} onChange={event => update(item.id, 'keep', event.target.checked)}/><strong>{item.keep ? 'Keep' : 'Discard'}</strong></label><span>{String(index + 1).padStart(2, '0')}</span></div><div className="ai-item-fields"><input className="ai-item-title" value={item.title} onChange={event => update(item.id, 'title', event.target.value)} placeholder="Action item title"/><button className="ai-delete" onClick={() => remove(item.id)} aria-label="Remove item"><Trash size={16}/></button><textarea value={item.description} onChange={event => update(item.id, 'description', event.target.value)} placeholder="Add a description…"/><div className="ai-item-grid"><label><User size={14}/><input value={item.assignee} onChange={event => update(item.id, 'assignee', event.target.value)} placeholder={user?.name || 'Assignee'}/></label><label><CalendarBlank size={14}/><input type="date" value={item.due} onChange={event => update(item.id, 'due', event.target.value)}/></label><label><Flag size={14}/><select value={item.priority} onChange={event => update(item.id, 'priority', event.target.value)}>{PRIORITIES.map(value => <option key={value}>{value}</option>)}</select></label><label><Users size={14}/><select value={item.area} onChange={event => update(item.id, 'area', event.target.value)}>{AREAS.map(value => <option key={value}>{value}</option>)}</select></label></div></div></article>)}</div></div>
    <div className="ai-review-footer"><span><strong>{selectedCount}</strong> items selected</span><button className="primary-button" disabled={!selectedCount} onClick={create}>Create {selectedCount} item{selectedCount === 1 ? '' : 's'}</button></div>
  </section>;
}
